export const NAVIGATION = {
    VIEW_WORK_REPORT: 'VIEW_WORK_REPORT',
    ADD_WORK_REPORT: 'ADD_WORK_REPORT',
    WORK_REPORT: 'Work Report',

    VIEW_MATERIAL: 'VIEW_MATERIAL',
    ADD_MATERIAL: 'ADD_MATERIAL',
    MATERIALS: 'Materials',

    SITE_SETTING: 'SITE_SETTING',
    WORK_CATEGORY: 'WORK_CATEGORY',
    ADD_SITE: 'ADD_SITE',
    VIEW_SITE: 'VIEW_SITE',
    SITE: 'SITE',
 
    HOME: 'Home',
    LOGIN: 'LOGIN',
    AUTH: 'AUTH',
    USER: 'USER',
}